server:
  port: 8080  # Приложение работает на порту 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentdb  # Подключение к MongoDB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080